### PR TITLE
Update IConstants.java

### PR DESCRIPTION
**Pull request by tachtler**
Change char DEGREE from (char) 176 to '°'.

### CODE REVIEW

**Comment by marioczpn** [comment]
nice change.. thanks!!

**Comment by tachtler** [comment]
Maybe, the change is NOT so good - maybe the line should be:

public static final char DEGREE = '\u00BA';

This is the original char like (char) 176 but in unicode, so tools like
StringUtils.substringBefore(lat, "\u00BA") will WORK! and
StringUtils.substringBefore(lat, "°") will maybe NOT WORK!

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Mario,

thank you, for your patience!

Klaus.

**Comment by marioczpn** [comment]
Sorry for the delay in reply to you! Nice finding and solution, a long time that I worked on this project and I really appreciate your contribution.

**Comment by tachtler** [comment]
Hi Mario,

no problem, thank you for your work.

Klaus.

**Pull request merged**
